README.md
The current link to Nitro route rules is broken, i've updated it!
Fix README.md link to Nitro route rules
=> Fix broken link to Nuxt nitro route rules

src/module.ts
i18n prefixes were not added to the sitemap loc and alternate urls.
Fixes #54 and probably #48 too.
Do we want to support the i18n strategy `prefix_and_default`?
=> fix: add url prefixes if `i18n.pages` is used

src/runtime/routes/sitemap.xsl.ts
Old url was a relative path and would therefore route locally (e.g. old url would route to "http://localhost:3000/nuxtseo.com/sitemap/guides/customising-ui"). I've simply added an "https://" schema so you're properly routed to the docs.
I've also removed a spare space before the link.
Quick fix, no issue created (sorry!)
=> fix: docs url on sidebar

src/utils.ts, test/unit/parsePages.test.ts
=> fix: correct pages flattening #153

src/runtime/routes/sitemap.xsl.ts
When the site name contains an ampersand (&) the xsl parser fails because the xsl becomes invalid.
fixes #182
=> fix: replace ampersand char with &amp; entity

.playground/nuxt.config.ts, src/runtime/nitro/sitemap/urlset/normalise.ts, test/integration/content/default.test.ts, test/integration/content/documentDriven.test.ts, test/integration/single/lastmod.test.ts
This Pull Request addresses the regex to comply with W3C specifications and adjusts the lastmod format in the sitemap file to adhere to W3C conventions.
- Corrected the regex to align with W3C specifications.
- Conducted tests to ensure the new regex works correctly in various use cases.
- [ X ] Reviewed and followed the project's contribution guidelines.
- [ X ] Tests have passed successfully.
- https://github.com/nuxt-modules/sitemap/issues/208
- https://github.com/nuxt-modules/sitemap/issues/206
=> fix: lastmod regex issue

src/runtime/types.ts
fix config `MultiSitemapsInput` types:
```ts
Property 'index' is incompatible with index signature.
Type '{ sitemap: string; }[]' has no properties in common with type 'Partial<SitemapDefinition>'.ts(2322)
```
=> fix: config `MultiSitemapsInput` types

src/module.ts, src/util/i18n.ts
will be needed for next version of Nuxt as with Bundler module resolution importing from a path isn't allowed
https://github.com/nuxt/nuxt/pull/24837
=> chore: import i18n types directly from module

src/runtime/nitro/sitemap/builder/sitemap.ts, src/runtime/nitro/sitemap/urlset/sources.ts
Try to get right host in danymic source eventhandler and give right right urls back.
It's useful in some saas platform with custom domain support, The sitemap need to be different for each Tenant
=> fix: forward host header to dynamic source endpoint

.github/workflows/release.yml, .github/workflows/test.yml, package.json
setup-node can reference the engine options in package.json as the node version.
- https://github.com/actions/setup-node?tab=readme-ov-file#usage
Using the `engine` makes it easier to manage workflow versions.
=> chore(ci): use `node-version-file` options

src/runtime/nitro/composables/defineSitemapEventHandler.ts, src/runtime/nitro/sitemap/nitro.ts, src/runtime/nitro/sitemap/urlset/sources.ts, src/util/nuxtSitemap.ts
`import type { foo }` and `import { type foo }` were mixed, so I refactored it to `import type { foo }`.
=> refactor: `import { type foo }` to `import type { foo }`

.github/renovate.json
As with Nuxt Scripts, I moved the Renovate config to `.github/`.
- nuxt/scripts#112
I also added configs for `eslint`, `eslint-plugin-*`, and `eslint-config-*`.
I think adding this rule will make it easier to merge library update PRs.
=> chore(ci): move renovate config

test/unit/extractSitemapMetaFromHtml.test.ts
N/A
N/A
- [] 📖 Documentation (updates to the documentation or readme)
- [] 👌 Enhancement (improving an existing functionality)
Added additional unit test coverage for `extractSitemapMetaFromHtml()` extracting valid and invalid `<img>` elements.
=> test: additional extractSitemapMetaFromHtml coverage

.playground/nuxt.config.ts, .playground/pages/prerender-video.vue, src/module.ts, src/prerender.ts, src/runtime/nitro/plugins/nuxt-content.ts, src/runtime/types.ts, src/util/extractSitemapMetaFromHtml.ts, test/unit/extractSitemapMetaFromHtml.test.ts
#299
- Added `discoverVideo` functionality to discover `<video>` tags in pre-rendered content. 
- Extended functionality of `extractSitemapMetaFromHtml` to extract attributes from `<video>` to provide required values for video sitemap(s). 
- Added tests to cover new `extractSitemapMetaFromHtml` functionality.
Example: screenshots below show the HTML and what the expected sitemap results would be. 
- `discoverVideos` is enabled by default to be consistent with `discoverImages` option.
- Required video sitemap tags (`thumbnail_loc`, `title`, `description`, `content_loc`) will return empty string in the event there are no value provided for that attribute. Google recommended these tags are 'required'.
- `src/runtime/nitro/plugins/nuxt-content.ts` will search only top-level `<video …
=> feat: video discovery

src/runtime/nitro/sitemap/nitro.ts
Relates to #311
https://github.com/nuxt-modules/sitemap/issues/311
Seems like we weren't checking the route rules per the docs, not sure how this happened.
=> fix: check for `robots` route rules

src/module.ts
https://github.com/nuxt-modules/sitemap/issues/311
Makes it easier to exclude i18n pages from the sitemap by allowing you to target either the i18n page name OR the default locale path.
=> fix: map `include`, `exclude` to i18n pages

src/module.ts, src/runtime/nitro/routes/sitemap.xsl.ts, src/runtime/nitro/routes/sitemap/[sitemap].xml.ts, src/runtime/nitro/routes/sitemap_index.xml.ts, src/runtime/nitro/routes/sitemaps/[sitemap].xml.ts, src/runtime/nitro/sitemap/builder/sitemap-index.ts, src/runtime/nitro/sitemap/nitro.ts, test/integration/chunks/default.ts, test/integration/chunks/generate.test.ts, test/integration/i18n/domains.test.ts, test/integration/i18n/dynamic-urls.test.ts, test/integration/i18n/filtering-include.test.ts, test/integration/i18n/filtering-regexp.test.ts, test/integration/i18n/filtering.test.ts, test/integration/i18n/generate.test.ts, test/integration/i18n/pages-multi.test.ts, test/integration/multi/defaults.ts, test/integration/multi/endpoints.ts, test/integration/multi/filtering.test.ts
n/a
Currently supporting multi-support is done through explicit build-time routes or using a middleware if they're chunked. This blocks us from generating runtime sitemaps when not chunking, as the paths are registered. This is an issue for multi-tenancy apps and is blocking https://github.com/nuxt-modules/sitemap/issues/265.
The paths change from `/{name}-sitemap.xml` to `/sitemap/{name}.xml` and are handled by Nitro named routes.
:warning: This is a breaking change if users have registered the multi-sitemap paths in Google Search Console, users should update these when upgrading.
=> feat!: new multi sitemaps paths

.github/ISSUE_TEMPLATE/01-feature-suggestion.yml, .github/ISSUE_TEMPLATE/02-bug-report.yml, .github/ISSUE_TEMPLATE/03-documentation.yml, .github/ISSUE_TEMPLATE/04-help-wanted.yml, .github/ISSUE_TEMPLATE/config.yml
related nuxt-modules/og-image#247
I added the same issue templates as I added in Nuxt Scripts.
=> chore(ci): add GitHub Issue templates

src/module.ts, src/runtime/nitro/routes/sitemap/[sitemap].xml.ts, src/runtime/nitro/routes/sitemap_index.xml.ts, src/runtime/nitro/sitemap/builder/sitemap-index.ts, src/runtime/types.ts, test/fixtures/i18n/nuxt.config.ts, test/integration/chunks/default.ts, test/integration/chunks/generate.test.ts, test/integration/i18n/domains.test.ts, test/integration/i18n/dynamic-urls.test.ts, test/integration/i18n/filtering-include.test.ts, test/integration/i18n/filtering-regexp.test.ts, test/integration/i18n/filtering.test.ts, test/integration/i18n/generate.test.ts, test/integration/i18n/pages-multi.test.ts, test/integration/multi/defaults.ts, test/integration/multi/endpoints.ts, test/integration/multi/filtering.test.ts
With this we change the path prefix for multi sitemaps to be `/__sitemap__`, some people may not like this so we make it configurable using `sitemapsPathPrefix`.
This will be released with the v6 and there's already a PR merged to cover the breaking change.
=> feat: `sitemapsPathPrefix` config

src/module.ts
Resolved #332
At module startup, when using the multiple sitemaps feature, currently you will recieve a false positive warning about using root config keys that will be ignored. Even though if you haven't defined them. This was because the check was an Object.keys(config).includes() which always returns true since the module `config` object is filled with default data.
Fixing this by changing the check to test if the values differ from the default ones.
=> fix(module): prevent false positive warning about ignored root keys

src/module.ts, src/runtime/types.ts, src/util/i18n.ts
https://github.com/nuxt-modules/sitemap/issues/330
Takes in account excluded locales so the users don't create empty sitemaps
=> fix(i18n): support excluded locales

src/module.ts, src/util/i18n.ts, test/integration/i18n/pages.only-locales.test.ts
Former PR reversed the logic of only locales. It's not excluding, it's including!
Added one test to document the behavior. 
Apologies for the former blunder.
=> fix(i18n): reverse only locales logic

package.json, pnpm-lock.yaml, src/module.ts, src/prerender.ts, src/runtime/nitro/sitemap/builder/sitemap.ts, src/runtime/types.ts, src/util/i18n.ts, src/util/nuxtSitemap.ts, test/integration/i18n/dynamic-urls.test.ts, test/integration/i18n/filtering.test.ts, test/integration/i18n/generate.test.ts, test/integration/i18n/prefix-and-default.test.ts, test/integration/i18n/prefix-except-default.test.ts, test/integration/i18n/prefix-iso.test.ts, test/integration/i18n/prefix-simple.test.ts, test/integration/i18n/route-rules.test.ts, test/integration/i18n/simple-trailing.test.ts, test/unit/i18n.test.ts, test/unit/parsePages.test.ts
https://github.com/nuxt-modules/sitemap/issues/350
Nuxt I18n renames the locale `iso` field to `language`. We need to now support both options.
=> feat(i18n): support Nuxt I18n v9

src/prerender.ts, src/runtime/nitro/sitemap/builder/sitemap.ts, src/runtime/nitro/sitemap/nitro.ts, test/unit/i18n.test.ts
https://github.com/nuxt-modules/sitemap/issues/333
URLs are not being deduped properly when we have i18n enabled.
=> fix(i18n): broken dedupe of loc and alternatives

package.json, pnpm-lock.yaml, src/module.ts, src/runtime/types.ts, test/fixtures/i18n-micro/locales/en.ts, test/fixtures/i18n-micro/locales/hr.ts, test/fixtures/i18n-micro/locales/ja.ts, test/fixtures/i18n-micro/locales/nl.ts, test/fixtures/i18n-micro/locales/zh.ts, test/fixtures/i18n-micro/nuxt.config.ts, test/fixtures/i18n-micro/pages/dynamic/[page].vue, test/fixtures/i18n-micro/pages/index.vue, test/fixtures/i18n-micro/pages/test.vue, test/fixtures/i18n-micro/server/routes/__sitemap.ts, test/fixtures/i18n-micro/server/routes/i18n-urls.ts
https://github.com/s00d/nuxt-i18n-micro/issues/11
As the i18n config has an identical signature we can support the https://github.com/s00d/nuxt-i18n-micro module out of the box without any extra effort :crossed_fingers:
=> feat: `nuxt-i18n-micro` module integration

src/runtime/server/sitemap/urlset/normalise.ts, test/integration/single/urlEncoded.test.ts
I'm building a blog nuxt app and using the sitemap module. While reading the sitemap, I recognized that the URLs containing umlauts like ä, ö, ü, ß and also á, à etc. are invalid. They get doubly encoded. For example: `/Bücher` should be encoded to `/B%C3%BCcher`, but now it is `/B%25C3%25BCcher`. The latter value is generated, when the first value (`/Bücher`) get URL encoded twice, so `decodeURI(decodeURI('B%25C3%25BCcher'))` will lead to `/Bücher` again. 
This PR is addressing this issue, also providing a test, to show that it really only gets encoded once. For this, a little helper function was introduced (`isEncoded`) to check if a string is already encoded or not.
I didn't add a test showing the issue, only one for the solution..
The failing eslint checks seems unrelated to the …
=> fix: doubly encoding of URLs

docs/content/2.guides/0.data-sources.md, docs/content/2.guides/0.multi-sitemaps.md, docs/content/2.guides/2.dynamic-urls.md, src/runtime/server/sitemap/urlset/sources.ts, src/runtime/server/sitemap/utils/extractSitemapXML.ts, test/unit/extractSitemapXML.ts
https://github.com/harlan-zw/nuxt-seo/issues/359
Load XML sitemaps as sources and it _just works_.
```ts
export default defineNuxtConfig({
sitemap: {
sources: [
'https://nuxtseo.com/sitemap.xml',
],
}
})
```
=> feat: external XML sitemaps as sources

docs/content/0.getting-started/0.introduction.md
The 'installation guide'-link pointed to the 'robots' installation guide, this corrects it to point to the sitemap guide.
=> docs: correct link to sitemap guide

docs/content/2.guides/6.customising-ui.md
XSL is the stylesheet for XML, XLS is a spreadsheet file format for Microsoft Excel
Replace references to XLS, a spreadsheet file format, with XSL, the stylesheet for XML to reduce confusion.
=> doc: rename references to xsl instead of xls

docs/content/2.guides/0.data-sources.md, docs/content/5.nitro-api/nitro-hooks.md, src/module.ts, src/runtime/server/routes/__sitemap__/debug.ts, src/runtime/server/sitemap/builder/sitemap-index.ts, src/runtime/server/sitemap/builder/sitemap.ts, src/runtime/types.ts, test/fixtures/sources-hook/nuxt.config.ts, test/fixtures/sources-hook/pages/index.vue, test/fixtures/sources-hook/server/api/dynamic-source.ts, test/fixtures/sources-hook/server/api/initial-source.ts, test/fixtures/sources-hook/server/plugins/sources-hook.ts, test/integration/hooks/sources-hook-simple.test.ts, test/unit/sourcesHook.test.ts
#433
There are instances where we won't know the sources of our sitemap until runtime (or headers required to fetch them). While we can work around this using the existing Nitro hooks, it means we work outside of the existing `sources` architecture. 
This PR allows us to modify the sources, allowing us to handle dynamic sitemap sources with minimal boilerplate.
```ts [server/plugins/sitemap.ts]
import { defineNitroPlugin } from 'nitropack/runtime'
import { getHeader } from 'h3'
export default defineNitroPlugin((nitroApp) => {
nitroApp.hooks.hook('sitemap:sources', async (ctx) => {
// Add a new source dynamically
ctx.sources.push('/api/runtime-urls')
// Modify existing sources to add headers
ctx.sources = ctx.sources.map(source => {
if (typeof source === 'object' && source.fetch) {
const …
```
=> feat: runtime sources

docs/content/2.guides/0.multi-sitemaps.md, docs/content/2.guides/9.chunking-sources.md, docs/content/4.api/0.config.md, src/module.ts, src/runtime/server/routes/sitemap/[sitemap].xml.ts, src/runtime/server/sitemap/builder/sitemap-index.ts, src/runtime/server/sitemap/builder/sitemap.ts, src/runtime/server/sitemap/nitro.ts, src/runtime/server/sitemap/utils/chunk.ts, src/runtime/types.ts, test/fixtures/multi-with-chunks/app.vue, test/fixtures/multi-with-chunks/nuxt.config.ts, test/fixtures/multi-with-chunks/server/api/posts.ts, test/fixtures/multi-with-chunks/server/api/products.ts, test/integration/multi/chunking-edge-cases.test.ts, test/integration/multi/chunking.test.ts
https://github.com/nuxt-modules/sitemap/issues/265
It's common that we want to split our sitemap into different sub-sitemaps, however, when we do this we lose the ability to have them automatically chunked based on the number of entries.
This PR allows us to have automatic chunks within a sub-sitemap, allowing us to handle very large sitemaps in multiple sitemaps, allowing for improving caching, debugging and SEO performance.
Support is experimental as the i18n behavior is not fully tested.
```ts
export default defineNuxtConfig({
sitemap: {
sitemaps: {
posts: {
sources: ['/api/posts'], // returns 10,000 posts
chunks: true, // Enable chunking with default size (1000)
},
products: {
sources: ['/api/products'], // returns 50,000 products
chunks: 5000, // Chunk into files with 5000 URLs each …
```
=> feat: automatic chunking for multi-sitemaps (experimental)

src/prerender.ts
Resolves: https://github.com/nuxt-modules/sitemap/issues/453
[This PR](https://github.com/nuxt/nuxt/pull/32252) reverted the Nitro version included in Nuxt. This means we still need to use the `nitropack` import until Nitro v3 is reintroduced (hopefully in Nuxt v5).
=> fix: nitro compatibility with v4

package.json, pnpm-lock.yaml, src/runtime/server/routes/__sitemap__/nuxt-content-urls-v3.ts
Resolves issue with newest version of Nuxt Content
https://github.com/nuxt/content/issues/3402
- [] 👌 Enhancement (improving an existing functionality)
There was an issue after updating to the latest version of nuxt content 3.6.0 where they changed their API to require a different import for `queryCollectionWithEvent` moving it to the normal `queryCollection`. This noted in their changelog linked below:
https://github.com/nuxt/content/releases/tag/v3.6.0
=> fix: support latest version of nuxt-content

package.json, pnpm-lock.yaml, src/content.ts
`asSitemapCollection` `schema` field isn't compatible with Nuxt Content 3.7. As far as I see, removing the `ZodRawShape` type constraint should fix it, which is analogous to the signature of `defineCollection`.
=> fix: `@nuxt/content` v3.7 compatibility

src/runtime/server/routes/__sitemap__/debug.ts
Could help resolve situations like this perhaps https://github.com/nuxt-modules/sitemap/issues/466
Just adding more of the website's configurations to the debug page for more in depth debugging out the sitemap output.
Also replaced a deprecated function call while I was there
=> fix: expose site config on debug endpoint

docs/content/2.guides/2.images-videos.md
Looks like the codeblocks here is breaking the code? :)
https://nuxtseo.com/docs/sitemap/guides/images-videos
=> docs: remove buggy codeblocks
